{
    a := 2;
    b := 4;
    c := 6;
    d := 8;
    
    puts('puts((a * b + c) * d);');
    puts((a * b + c) * d);
    
    puts('puts(a * b + c * d);');
    puts(a * b + c * d);

    puts('puts(a * (b + c) * d);');
    puts(a * (b + c) * d);
    
    if c > d then {
        puts('c > d')
    } else {
        puts('NOT c > d')
    };

    if c < d then {
        puts('c < d')
    } 
    else {
        puts('NOT c < d')
    }
}
